version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: draw-and-guess-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: draw_and_guess_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - draw-and-guess-network

  valkey:
    image: valkey/valkey:7.2-alpine
    container_name: draw-and-guess-valkey
    ports:
      - "6379:6379"
    networks:
      - draw-and-guess-network
    command: valkey-server --appendonly yes
    volumes:
      - valkey_data:/data

volumes:
  mongodb_data:
  valkey_data:

networks:
  draw-and-guess-network:
    driver: bridge
