apiVersion: v1
kind: PersistentVolume
metadata:
  name: valkey-pv-0
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/data/valkey-0
    type: DirectoryOrCreate
