package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"draw-and-guess-server/internal/graph/model"
	"fmt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	email := ""
	if input.Email != nil {
		email = *input.Email
	}
	avatarURL := ""
	if input.AvatarURL != nil {
		avatarURL = *input.AvatarURL
	}

	created, err := r.UserService.CreateUser(ctx, input.Username, input.DisplayName, email, avatarURL)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:          fmt.Sprintf("%d", created.ID),
		Username:    created.Username,
		DisplayName: created.DisplayName,
		Email:       &created.Email,
		AvatarURL:   &created.AvatarURL,
		CreatedAt:   created.CreatedAt,
		UpdatedAt:   created.UpdatedAt,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, username string, input model.UpdateUserInput) (*model.User, error) {
	updated, err := r.UserService.UpdateUser(ctx, username, input.DisplayName, input.Email, input.AvatarURL)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:          fmt.Sprintf("%d", updated.ID),
		Username:    updated.Username,
		DisplayName: updated.DisplayName,
		Email:       &updated.Email,
		AvatarURL:   &updated.AvatarURL,
		CreatedAt:   updated.CreatedAt,
		UpdatedAt:   updated.UpdatedAt,
	}, nil
}

// CreateGameRoom is the resolver for the createGameRoom field.
func (r *mutationResolver) CreateGameRoom(ctx context.Context, input model.CreateGameRoomInput) (*model.GameRoom, error) {
	panic(fmt.Errorf("not implemented: CreateGameRoom - createGameRoom"))
}

// JoinGameRoom is the resolver for the joinGameRoom field.
func (r *mutationResolver) JoinGameRoom(ctx context.Context, roomID string, username string) (*model.GameRoom, error) {
	panic(fmt.Errorf("not implemented: JoinGameRoom - joinGameRoom"))
}

// LeaveGameRoom is the resolver for the leaveGameRoom field.
func (r *mutationResolver) LeaveGameRoom(ctx context.Context, roomID string, username string) (*model.GameRoom, error) {
	panic(fmt.Errorf("not implemented: LeaveGameRoom - leaveGameRoom"))
}

// StartGame is the resolver for the startGame field.
func (r *mutationResolver) StartGame(ctx context.Context, roomID string) (*model.GameRoom, error) {
	panic(fmt.Errorf("not implemented: StartGame - startGame"))
}

// DeleteGameRoom is the resolver for the deleteGameRoom field.
func (r *mutationResolver) DeleteGameRoom(ctx context.Context, roomID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteGameRoom - deleteGameRoom"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, username string) (*model.User, error) {
	user, err := r.UserService.GetUser(ctx, username)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:          fmt.Sprintf("%d", user.ID),
		Username:    user.Username,
		DisplayName: user.DisplayName,
		Email:       &user.Email,
		AvatarURL:   &user.AvatarURL,
		CreatedAt:   user.CreatedAt,
		UpdatedAt:   user.UpdatedAt,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.GetAllUsers(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.User, len(users))
	for i, u := range users {
		result[i] = &model.User{
			ID:          fmt.Sprintf("%d", u.ID),
			Username:    u.Username,
			DisplayName: u.DisplayName,
			Email:       &u.Email,
			AvatarURL:   &u.AvatarURL,
			CreatedAt:   u.CreatedAt,
			UpdatedAt:   u.UpdatedAt,
		}
	}
	return result, nil
}

// GameRoom is the resolver for the gameRoom field.
func (r *queryResolver) GameRoom(ctx context.Context, id string) (*model.GameRoom, error) {
	panic(fmt.Errorf("not implemented: GameRoom - gameRoom"))
}

// GameRooms is the resolver for the gameRooms field.
func (r *queryResolver) GameRooms(ctx context.Context, gameType *model.GameType) ([]*model.GameRoom, error) {
	panic(fmt.Errorf("not implemented: GameRooms - gameRooms"))
}

// RandomOXQuiz is the resolver for the randomOXQuiz field.
func (r *queryResolver) RandomOXQuiz(ctx context.Context) (*model.OXQuiz, error) {
	quiz, err := r.QuizService.GetRandomOXQuiz(ctx)
	if err != nil {
		return nil, err
	}

	return &model.OXQuiz{
		ID:          fmt.Sprintf("%d", quiz.ID),
		Category:    quiz.Category,
		Difficulty:  quiz.Difficulty,
		Question:    quiz.Question,
		Answer:      quiz.Answer,
		Explanation: &quiz.Explanation,
		UsageCount:  int32(quiz.UsageCount),
		IsActive:    quiz.IsActive,
		CreatedAt:   quiz.CreatedAt,
		UpdatedAt:   quiz.UpdatedAt,
	}, nil
}

// RandomQAQuiz is the resolver for the randomQAQuiz field.
func (r *queryResolver) RandomQAQuiz(ctx context.Context) (*model.GeneralQuiz, error) {
	quiz, err := r.QuizService.GetRandomQAQuiz(ctx)
	if err != nil {
		return nil, err
	}

	return &model.GeneralQuiz{
		ID:          fmt.Sprintf("%d", quiz.ID),
		Category:    quiz.Category,
		Difficulty:  quiz.Difficulty,
		Question:    quiz.Question,
		Options:     quiz.Options,
		Answer:      int32(quiz.Answer),
		Explanation: &quiz.Explanation,
		ImageURL:    &quiz.ImageURL,
		UsageCount:  int32(quiz.UsageCount),
		IsActive:    quiz.IsActive,
		CreatedAt:   quiz.CreatedAt,
		UpdatedAt:   quiz.UpdatedAt,
	}, nil
}

// PlayerStats is the resolver for the playerStats field.
func (r *queryResolver) PlayerStats(ctx context.Context, username string, gameType *string) ([]*model.PlayerStats, error) {
	panic(fmt.Errorf("not implemented: PlayerStats - playerStats"))
}

// Leaderboard is the resolver for the leaderboard field.
func (r *queryResolver) Leaderboard(ctx context.Context, gameType string, limit *int32) ([]*model.PlayerStats, error) {
	panic(fmt.Errorf("not implemented: Leaderboard - leaderboard"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
