apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: data
spec:
  type: NodePort
  selector:
    app: go-server  # Deployment의 labels와 일치해야 함
  ports:
    - protocol: TCP
      port: 80         # 서비스 내부용 (다른 Pod이 접속할 때)
      targetPort: 8080 # 실제 앱 포트 (Go 서버 설정과 일치해야 함)
      nodePort: 8080  # 외부 접속용 (서버IP:30080 으로 접속)