// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// 답변 제출 결과를 나타냅니다.
// Apollo Client에서 Optimistic UI와 즉각적인 피드백을 위해 사용됩니다.
type AnswerResult struct {
	// 제출 성공 여부
	Success bool `json:"success"`
	// 정답 여부 (제출자에게만 전달)
	IsCorrect bool `json:"isCorrect"`
	// 획득한 점수 (정답 시 100점)
	EarnedScore int32 `json:"earnedScore"`
	// 현재 총 점수
	TotalScore int32 `json:"totalScore"`
	// 정답 (라운드 종료 후에만 제공되지만, 즉시 피드백용)
	CorrectAnswer *string `json:"correctAnswer,omitempty"`
	// 설명 (선택사항)
	Explanation *string `json:"explanation,omitempty"`
}

// 게임방 채팅 메시지입니다.
// WebSocket을 통해 실시간으로 전달됩니다.
type ChatMessage struct {
	// 고유 메시지 ID
	ID string `json:"id"`
	// 메시지가 전송된 게임방 ID
	RoomID string `json:"roomId"`
	// 발신자 사용자명
	Username string `json:"username"`
	// 발신자 표시 이름
	DisplayName string `json:"displayName"`
	// 메시지 내용 (최대 500자)
	Message string `json:"message"`
	// 전송 시각
	Timestamp time.Time `json:"timestamp"`
}

// 새 게임방 생성을 위한 입력 데이터
// 생성자가 자동으로 방장이 되며 첫 번째 플레이어로 입장합니다.
type CreateGameRoomInput struct {
	// 게임방 이름 (1-50자, 로비에 표시)
	Name string `json:"name"`
	// 게임 모드 (OX, QA, WORDCHAIN 중 선택)
	GameType GameType `json:"gameType"`
	// 최대 플레이어 수 (2-10명, 권장: 4-6명)
	MaxUsers int32 `json:"maxUsers"`
	// 총 라운드 수 (1-20, 권장: 3-10)
	TotalRounds int32 `json:"totalRounds"`
	// 라운드당 제한 시간 (초 단위, 10-300초, 기본값: 30초)
	RoundTimeLimit *int32 `json:"roundTimeLimit,omitempty"`
	// 방장 사용자 ID (게임방 생성자)
	HostUserID string `json:"hostUserId"`
	// 비공개 방 여부 (true: 비밀번호 필요, false: 누구나 입장 가능)
	IsPrivate *bool `json:"isPrivate,omitempty"`
	// 게임방 비밀번호 (isPrivate=true 시 필수, 4-20자)
	Password *string `json:"password,omitempty"`
}

// 새 사용자 계정 생성을 위한 입력 데이터
type CreateUserInput struct {
	// 로그인용 식별자 (3-20자)
	HangeID string `json:"hangeId"`
	// 고유 사용자명 (3-20자) (선택사항)
	Name *string `json:"name,omitempty"`
	// 프로필 이미지 URL (선택사항)
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

// 에러 이벤트 정보입니다.
// 게임 중 발생한 에러를 클라이언트에 전달합니다.
type ErrorEvent struct {
	// 에러 코드 (예: INVALID_ANSWER, ROOM_FULL, PERMISSION_DENIED)
	Code string `json:"code"`
	// 사용자에게 표시할 에러 메시지 (다국어 지원 권장)
	Message string `json:"message"`
	// 에러 발생 시각
	Timestamp time.Time `json:"timestamp"`
}

// 게임 전역 설정 정보입니다.
// 서버에서 관리하며 클라이언트는 이 값을 참고하여 UI를 구성합니다.
type GameConfig struct {
	// 최대 플레이어 수 제한 (현재: 8명)
	MaxUsers int32 `json:"maxUsers"`
	// 라운드당 제한 시간 (초, 현재: 30초)
	RoundDuration int32 `json:"roundDuration"`
	// 그리기 제한 시간 (초, 향후 기능)
	DrawingTime int32 `json:"drawingTime"`
	// 추측 제한 시간 (초, 향후 기능)
	GuessingTime int32 `json:"guessingTime"`
	// 게임당 기본 라운드 수 (현재: 5)
	RoundsPerGame int32 `json:"roundsPerGame"`
}

// 게임 이벤트 상세 정보입니다.
// WebSocket을 통해 실시간으로 전달되며, 클라이언트는 type에 따라 적절한 처리를 수행해야 합니다.
type GameEvent struct {
	// 이벤트 타입 (어떤 이벤트가 발생했는지)
	Type GameEventType `json:"type"`
	// 이벤트가 발생한 게임방 ID
	RoomID string `json:"roomId"`
	// 이벤트 관련 플레이어 사용자명 (선택사항)
	Username *string `json:"username,omitempty"`
	// 이벤트 관련 플레이어 표시 이름 (선택사항)
	DisplayName *string `json:"displayName,omitempty"`
	// 추가 데이터 (JSON 문자열, type에 따라 다름)
	Data *string `json:"data,omitempty"`
	// 이벤트 발생 시각
	Timestamp time.Time `json:"timestamp"`
}

// 게임 종료 시 플레이어 순위 정보
type GameRanking struct {
	// 순위 (1위, 2위, ...)
	Rank int32 `json:"rank"`
	// 사용자 ID
	UserID string `json:"userId"`
	// 사용자 이름
	Name string `json:"name"`
	// 최종 점수
	Score int32 `json:"score"`
}

// 게임 종료 결과 정보
type GameResult struct {
	// 게임방 정보
	Room *GameRoom `json:"room"`
	// 순위 목록 (점수 높은 순)
	Rankings []*GameRanking `json:"rankings"`
	// 우승자 이름
	Winner string `json:"winner"`
}

// 멀티플레이어 게임 세션을 나타냅니다.
// OX 퀴즈, QA 퀴즈, 끝말잇기 게임 모드를 지원합니다.
type GameRoom struct {
	// 고유 게임방 식별자 (UUID)
	ID string `json:"id"`
	// 게임방 표시 이름
	Name string `json:"name"`
	// 게임 모드: OX, QA, 또는 WORDCHAIN
	GameType GameType `json:"gameType"`
	// 현재 게임 상태
	Status GameRoomStatus `json:"status"`
	// 현재 라운드 번호 (1부터 시작)
	CurrentRound int32 `json:"currentRound"`
	// 총 라운드 수 (기본값: 5)
	TotalRounds int32 `json:"totalRounds"`
	// 라운드당 제한 시간 (초 단위, 기본값: 30초)
	RoundTimeLimit int32 `json:"roundTimeLimit"`
	// 게임방 내 사용자 목록
	Users []*GameUser `json:"users"`
	// 최대 사용자 수 (2-10명)
	MaxUsers int32 `json:"maxUsers"`
	// 방장 사용자 ID
	HostUserID string `json:"hostUserId"`
	// 현재 게임에서 사용된 퀴즈 ID 목록
	UsedQuizIds []string `json:"usedQuizIds"`
	// 비공개방 여부
	IsPrivate bool `json:"isPrivate"`
	// 게임방 비밀번호 (비공개방만)
	Password *string `json:"password,omitempty"`
	// 게임방 생성 시각
	CreatedAt time.Time `json:"createdAt"`
	// 끝말잇기 게임 - 마지막 단어
	WordchainLastWord *string `json:"wordchainLastWord,omitempty"`
	// 끝말잇기 게임 - 사용된 단어 목록
	WordchainUsedWords []string `json:"wordchainUsedWords,omitempty"`
	// 끝말잇기 게임 - 현재 턴 플레이어 ID
	CurrentTurnUserID *string `json:"currentTurnUserId,omitempty"`
	// 끝말잇기 게임 - 턴 시작 시간
	WordchainTurnStartTime *time.Time `json:"wordchainTurnStartTime,omitempty"`
}

// 게임방 내 사용자 정보입니다.
// WebSocket을 통해 실시간으로 업데이트됩니다.
type GameUser struct {
	// 사용자의 고유 id
	UserID string `json:"userId"`
	// 사용자의 고유 사용자명
	Name string `json:"name"`
	// 현재 게임에서 획득한 점수 (정답 시 +100점)
	Score int32 `json:"score"`
	// 준비 완료 여부 (게임 시작 전, 방장 제외 모든 사용자 true 필요)
	IsReady bool `json:"isReady"`
}

// 4지선다 퀴즈를 나타냅니다.
// QA 게임 모드에서 사용됩니다.
type GeneralQuiz struct {
	// 고유 퀴즈 ID (Snowflake)
	ID string `json:"id"`
	// 퀴즈 카테고리 (예: 수학, 지리)
	Category string `json:"category"`
	// 난이도: 1-5 (1=Easy, 2=Normal, 3=Hard, 4=VeryHard, 5=Extreme)
	Difficulty int32 `json:"difficulty"`
	// 문제 텍스트
	Question string `json:"question"`
	// 4개의 선택지 배열
	Options []string `json:"options"`
	// 정답 인덱스 (0-3)
	Answer int32 `json:"answer"`
	// 정답 설명 (선택사항)
	Explanation *string `json:"explanation,omitempty"`
	// 시각적 문제를 위한 이미지 URL (선택사항)
	ImageURL *string `json:"imageUrl,omitempty"`
	// 이 퀴즈가 사용된 횟수
	UsageCount int32 `json:"usageCount"`
	// 퀴즈 활성화 여부
	IsActive bool `json:"isActive"`
	// 퀴즈 생성 시각
	CreatedAt time.Time `json:"createdAt"`
	// 마지막 업데이트 시각
	UpdatedAt time.Time `json:"updatedAt"`
}

// 게임방 초대 정보입니다.
// 사용자는 알림을 통해 초대를 받고 수락/거절할 수 있습니다.
type Invitation struct {
	// 고유 초대 ID (UUID)
	ID string `json:"id"`
	// 초대 대상 게임방 ID
	RoomID string `json:"roomId"`
	// 초대 대상 게임방 정보
	Room *GameRoom `json:"room"`
	// 초대한 사용자 ID
	InviterID string `json:"inviterId"`
	// 초대한 사용자 정보
	Inviter *User `json:"inviter"`
	// 초대받은 사용자 ID
	InviteeID string `json:"inviteeId"`
	// 초대받은 사용자 정보
	Invitee *User `json:"invitee"`
	// 현재 초대 상태
	Status InviteStatus `json:"status"`
	// 초대 생성 시각
	CreatedAt time.Time `json:"createdAt"`
	// 초대 만료 시각 (생성 후 24시간)
	ExpiresAt time.Time `json:"expiresAt"`
}

// 데이터 변경을 위한 뮤테이션입니다.
// 서버 상태를 변경하는 모든 작업은 mutation을 통해 수행됩니다.
type Mutation struct {
}

// OX 퀴즈 (참/거짓 문제)를 나타냅니다.
// OX 게임 모드에서 사용됩니다.
type OXQuiz struct {
	// 고유 퀴즈 ID (Snowflake)
	ID string `json:"id"`
	// 퀴즈 카테고리 (예: 과학, 역사)
	Category string `json:"category"`
	// 난이도: 1-5 (1=Easy, 2=Normal, 3=Hard, 4=VeryHard, 5=Extreme)
	Difficulty int32 `json:"difficulty"`
	// 문제 텍스트
	Question string `json:"question"`
	// 정답: true 또는 false
	Answer bool `json:"answer"`
	// 정답 설명 (선택사항)
	Explanation *string `json:"explanation,omitempty"`
	// 이 퀴즈가 사용된 횟수
	UsageCount int32 `json:"usageCount"`
	// 퀴즈 활성화 여부
	IsActive bool `json:"isActive"`
	// 퀴즈 생성 시각
	CreatedAt time.Time `json:"createdAt"`
	// 마지막 업데이트 시각
	UpdatedAt time.Time `json:"updatedAt"`
}

// OX 퀴즈 (정답 제외 버전) - 클라이언트 전송용
// 게임 시작 시 여러 문제를 한 번에 전송할 때 사용합니다.
// 정답과 해설은 서버에 저장되어 있으며, 라운드 종료 시 ROUND_ENDED 이벤트로 제공됩니다.
type OXQuizWithoutAnswer struct {
	// 고유 퀴즈 ID
	ID string `json:"id"`
	// 퀴즈 카테고리
	Category string `json:"category"`
	// 난이도: 1-5 (1=Easy, 2=Normal, 3=Hard, 4=VeryHard, 5=Extreme)
	Difficulty int32 `json:"difficulty"`
	// 문제 텍스트
	Question string `json:"question"`
}

// 4지선다 퀴즈 (정답 제외 버전) - 클라이언트 전송용
// 게임 시작 시 여러 문제를 한 번에 전송할 때 사용합니다.
// 정답과 해설은 서버에 저장되어 있으며, 라운드 종료 시 ROUND_ENDED 이벤트로 제공됩니다.
type QAQuizWithoutAnswer struct {
	// 고유 퀴즈 ID
	ID string `json:"id"`
	// 퀴즈 카테고리
	Category string `json:"category"`
	// 난이도: 1-5 (1=Easy, 2=Normal, 3=Hard, 4=VeryHard, 5=Extreme)
	Difficulty int32 `json:"difficulty"`
	// 문제 텍스트
	Question string `json:"question"`
	// 4개의 선택지 배열
	Options []string `json:"options"`
	// 시각적 문제를 위한 이미지 URL (선택사항)
	ImageURL *string `json:"imageUrl,omitempty"`
}

// 데이터 조회를 위한 쿼리입니다.
// 읽기 전용 작업이며 서버 상태를 변경하지 않습니다.
type Query struct {
}

// 실시간 데이터 업데이트를 위한 구독입니다.
// WebSocket 연결을 통해 서버에서 클라이언트로 이벤트를 푸시합니다.
//
// **연결 방법:**
// 1. WebSocket 엔드포인트 연결: ws://server/graphql
// 2. GraphQL Subscription 시작
// 3. 이벤트 수신 대기
//
// **주의사항:**
// - 각 구독은 별도의 WebSocket 연결 필요
// - 불필요한 구독은 해제하여 리소스 절약
// - 연결 끊김 시 자동 재연결 구현 권장
type Subscription struct {
}

// 게임방 설정 변경을 위한 입력 데이터 (모든 필드 선택사항)
// 방장만 실행 가능하며, 게임 진행 중에는 변경 불가합니다.
type UpdateGameRoomInput struct {
	// 새로운 게임방 이름
	Name *string `json:"name,omitempty"`
	// 새로운 최대 플레이어 수 (현재 인원보다 작게 설정 불가)
	MaxUsers *int32 `json:"maxUsers,omitempty"`
	// 새로운 총 라운드 수
	TotalRounds *int32 `json:"totalRounds,omitempty"`
	// 새로운 라운드당 제한 시간 (초 단위, 10-300초)
	RoundTimeLimit *int32 `json:"roundTimeLimit,omitempty"`
	// 비공개 설정 변경 (true로 변경 시 password 필수)
	IsPrivate *bool `json:"isPrivate,omitempty"`
	// 새로운 비밀번호 (빈 문자열로 비밀번호 제거 가능)
	Password *string `json:"password,omitempty"`
}

// 사용자 프로필 업데이트를 위한 입력 데이터 (모든 필드 선택사항)
type UpdateUserInput struct {
	// 새로운 프로필 이미지 URL
	AvatarURL *string `json:"avatarUrl,omitempty"`
	// 새로운 레벨
	Level *int32 `json:"level,omitempty"`
	// 새로운 일반 재화
	Credit *int32 `json:"credit,omitempty"`
}

// 유저 통계 업데이트를 위한 입력 데이터
type UpdateUserStatsInput struct {
	// 사용자 ID
	UserID string `json:"userId"`
	// 게임 타입 (OX, QA, WORDCHAIN 등)
	GameType string `json:"gameType"`
	// 개인전 승리 추가 (선택사항)
	SoloWins *int32 `json:"soloWins,omitempty"`
	// 개인전 패배 추가 (선택사항)
	SoloLoses *int32 `json:"soloLoses,omitempty"`
	// 개인전 최고 점수 (선택사항, 기존 최고점보다 높을 때만 업데이트)
	SoloBestScore *int32 `json:"soloBestScore,omitempty"`
	// 팀전 승리 추가 (선택사항)
	TeamWins *int32 `json:"teamWins,omitempty"`
	// 팀전 패배 추가 (선택사항)
	TeamLoses *int32 `json:"teamLoses,omitempty"`
	// 팀전 MVP 횟수 추가 (선택사항)
	TeamMVPCnt *int32 `json:"teamMVPCnt,omitempty"`
	// 총 게임 수 추가
	TotalGames int32 `json:"totalGames"`
	// 총 점수 추가
	TotalScore int32 `json:"totalScore"`
}

// 게임 플레이어 계정을 나타냅니다.
// name은 고유하며 주요 식별자로 사용됩니다.
type User struct {
	// 고유 식별자 (MongoDB ObjectID)
	ID string `json:"id"`
	// 로그인용 식별자 (3-20자, 로그인 전용)
	HangeID string `json:"hangeId"`
	// 고유 사용자명 (3-20자, 주요 식별자)
	Name string `json:"name"`
	// 프로필 이미지 URL
	AvatarURL *string `json:"avatarUrl,omitempty"`
	// 플레이어 레벨
	Level int32 `json:"level"`
	// 일반 재화 (게임 플레이로 획득)
	Credit int32 `json:"credit"`
	// 소속 길드 ID (선택사항)
	GuildID *string `json:"guildId,omitempty"`
	// 계정 생성 시각
	CreatedAt time.Time `json:"createdAt"`
	// 마지막 업데이트 시각
	UpdatedAt time.Time `json:"updatedAt"`
}

// 사용자의 연결 상태 정보입니다.
// 실시간 온라인/오프라인 표시에 사용됩니다.
type UserConnection struct {
	// 사용자명
	Username string `json:"username"`
	// 연결 상태 (true: 온라인, false: 오프라인)
	IsConnected bool `json:"isConnected"`
	// 마지막 접속 시각
	LastSeen time.Time `json:"lastSeen"`
	// 핑 (밀리초, 네트워크 지연시간)
	Ping *int32 `json:"ping,omitempty"`
}

// 사용자의 게임 타입별 통계 정보입니다.
// 리더보드 및 프로필 화면에서 사용됩니다.
type UserStats struct {
	// 사용자명
	Username string `json:"username"`
	// 게임 타입 (OX, QA, WORDCHAIN)
	GameType string `json:"gameType"`
	// 총 플레이한 게임 수
	TotalGames int32 `json:"totalGames"`
	// 총 승리 횟수 (1등 횟수)
	TotalWins int32 `json:"totalWins"`
	// 총 획득 점수 (모든 게임 누적)
	TotalScore int32 `json:"totalScore"`
	// 통계 생성 시각
	CreatedAt time.Time `json:"createdAt"`
	// 마지막 업데이트 시각
	UpdatedAt time.Time `json:"updatedAt"`
}

// 끝말잇기 게임의 시작 단어 정보입니다.
// 일본어 히라가나 또는 카타카나 단어입니다.
type WordchainPrompt struct {
	// 시작 단어 (히라가나 또는 카타카나, 2자 이상)
	Word string `json:"word"`
	// 힌트 (선택사항, 단어의 의미)
	Hint *string `json:"hint,omitempty"`
}

// 게임 내에서 발생하는 이벤트 타입입니다.
// WebSocket gameEvent 구독을 통해 실시간으로 수신됩니다.
// 클라이언트는 이 이벤트에 따라 UI를 업데이트하고 효과음/애니메이션을 재생할 수 있습니다.
type GameEventType string

const (
	// 플레이어가 게임방에 입장함
	GameEventTypeUserJoined GameEventType = "user_JOINED"
	// 플레이어가 게임방에서 퇴장함
	GameEventTypeUserLeft GameEventType = "user_LEFT"
	// 플레이어가 준비 완료 상태로 변경함
	GameEventTypeUserReady GameEventType = "user_READY"
	// 방장이 변경됨 (이전 방장 퇴장 또는 권한 양도)
	GameEventTypeHostChanged GameEventType = "HOST_CHANGED"
	// 새 라운드가 시작됨 (새 퀴즈 제시)
	GameEventTypeRoundStarted GameEventType = "ROUND_STARTED"
	// 라운드가 종료됨 (정답 공개 및 점수 갱신)
	GameEventTypeRoundEnded GameEventType = "ROUND_ENDED"
	// 플레이어가 답변을 제출함 (다른 플레이어에게 알림)
	GameEventTypeAnswerSubmitted GameEventType = "ANSWER_SUBMITTED"
	// 정답을 맞춤 (본인에게만 전송, +100점)
	GameEventTypeCorrectAnswer GameEventType = "CORRECT_ANSWER"
	// 오답 (본인에게만 전송, 점수 변화 없음)
	GameEventTypeWrongAnswer GameEventType = "WRONG_ANSWER"
	// 게임이 종료됨 (최종 결과 및 순위 표시)
	GameEventTypeGameEnded GameEventType = "GAME_ENDED"
)

var AllGameEventType = []GameEventType{
	GameEventTypeUserJoined,
	GameEventTypeUserLeft,
	GameEventTypeUserReady,
	GameEventTypeHostChanged,
	GameEventTypeRoundStarted,
	GameEventTypeRoundEnded,
	GameEventTypeAnswerSubmitted,
	GameEventTypeCorrectAnswer,
	GameEventTypeWrongAnswer,
	GameEventTypeGameEnded,
}

func (e GameEventType) IsValid() bool {
	switch e {
	case GameEventTypeUserJoined, GameEventTypeUserLeft, GameEventTypeUserReady, GameEventTypeHostChanged, GameEventTypeRoundStarted, GameEventTypeRoundEnded, GameEventTypeAnswerSubmitted, GameEventTypeCorrectAnswer, GameEventTypeWrongAnswer, GameEventTypeGameEnded:
		return true
	}
	return false
}

func (e GameEventType) String() string {
	return string(e)
}

func (e *GameEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameEventType", str)
	}
	return nil
}

func (e GameEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameEventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameEventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 게임방의 현재 상태를 나타냅니다.
// 클라이언트는 이 값에 따라 UI를 다르게 표시해야 합니다.
type GameRoomStatus string

const (
	// 대기 중 (플레이어 모집 중, 게임 시작 전)
	GameRoomStatusWaiting GameRoomStatus = "WAITING"
	// 게임 진행 중 (라운드 진행 중, 플레이어 입장 불가)
	GameRoomStatusPlaying GameRoomStatus = "PLAYING"
	// 게임 종료 (최종 결과 표시, 곧 대기 상태로 전환)
	GameRoomStatusFinished GameRoomStatus = "FINISHED"
)

var AllGameRoomStatus = []GameRoomStatus{
	GameRoomStatusWaiting,
	GameRoomStatusPlaying,
	GameRoomStatusFinished,
}

func (e GameRoomStatus) IsValid() bool {
	switch e {
	case GameRoomStatusWaiting, GameRoomStatusPlaying, GameRoomStatusFinished:
		return true
	}
	return false
}

func (e GameRoomStatus) String() string {
	return string(e)
}

func (e *GameRoomStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameRoomStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameRoomStatus", str)
	}
	return nil
}

func (e GameRoomStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameRoomStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameRoomStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 게임 모드를 나타냅니다.
// 클라이언트는 게임방 생성 시 이 값을 선택해야 합니다.
type GameType string

const (
	// OX 퀴즈 게임 (참/거짓 문제, 빠른 판단력 게임)
	GameTypeOx GameType = "OX"
	// 4지선다 퀴즈 게임 (일반 지식 퀴즈)
	GameTypeQa GameType = "QA"
	// 끝말잇기 게임 (일본어 히라가나/카타카나 단어 연결)
	GameTypeWordchain GameType = "WORDCHAIN"
	// 그림 맞추기 게임 (그림을 그리고 정답 맞추기)
	GameTypeDrawing GameType = "DRAWING"
)

var AllGameType = []GameType{
	GameTypeOx,
	GameTypeQa,
	GameTypeWordchain,
	GameTypeDrawing,
}

func (e GameType) IsValid() bool {
	switch e {
	case GameTypeOx, GameTypeQa, GameTypeWordchain, GameTypeDrawing:
		return true
	}
	return false
}

func (e GameType) String() string {
	return string(e)
}

func (e *GameType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameType", str)
	}
	return nil
}

func (e GameType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 게임방 초대 상태를 나타냅니다.
// 초대는 24시간 후 자동으로 만료됩니다.
type InviteStatus string

const (
	// 대기 중 (초대받은 사용자의 응답 대기)
	InviteStatusPending InviteStatus = "PENDING"
	// 수락됨 (사용자가 게임방에 입장함)
	InviteStatusAccepted InviteStatus = "ACCEPTED"
	// 거절됨 (사용자가 초대를 거절함)
	InviteStatusRejected InviteStatus = "REJECTED"
	// 만료됨 (24시간 경과 또는 게임방 삭제)
	InviteStatusExpired InviteStatus = "EXPIRED"
)

var AllInviteStatus = []InviteStatus{
	InviteStatusPending,
	InviteStatusAccepted,
	InviteStatusRejected,
	InviteStatusExpired,
}

func (e InviteStatus) IsValid() bool {
	switch e {
	case InviteStatusPending, InviteStatusAccepted, InviteStatusRejected, InviteStatusExpired:
		return true
	}
	return false
}

func (e InviteStatus) String() string {
	return string(e)
}

func (e *InviteStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InviteStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InviteStatus", str)
	}
	return nil
}

func (e InviteStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InviteStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InviteStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// OX 퀴즈의 선택지입니다.
// submitAnswer 뮤테이션에서 'true' 또는 'false' 문자열로 전달합니다.
type OXChoice string

const (
	// 참 (정답: true)
	OXChoiceO OXChoice = "O"
	// 거짓 (정답: false)
	OXChoiceX OXChoice = "X"
)

var AllOXChoice = []OXChoice{
	OXChoiceO,
	OXChoiceX,
}

func (e OXChoice) IsValid() bool {
	switch e {
	case OXChoiceO, OXChoiceX:
		return true
	}
	return false
}

func (e OXChoice) String() string {
	return string(e)
}

func (e *OXChoice) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OXChoice(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OXChoice", str)
	}
	return nil
}

func (e OXChoice) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OXChoice) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OXChoice) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
