// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateGameRoomInput struct {
	Name         string   `json:"name"`
	GameType     GameType `json:"gameType"`
	MaxPlayers   int32    `json:"maxPlayers"`
	TotalRounds  int32    `json:"totalRounds"`
	HostUsername string   `json:"hostUsername"`
}

type CreateUserInput struct {
	Username    string  `json:"username"`
	DisplayName string  `json:"displayName"`
	Email       *string `json:"email,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
}

type GameRoom struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	GameType     GameType   `json:"gameType"`
	Status       GameStatus `json:"status"`
	CurrentRound int32      `json:"currentRound"`
	TotalRounds  int32      `json:"totalRounds"`
	Players      []*Player  `json:"players"`
	MaxPlayers   int32      `json:"maxPlayers"`
	HostUsername string     `json:"hostUsername"`
	CreatedAt    time.Time  `json:"createdAt"`
}

type GeneralQuiz struct {
	ID          string    `json:"id"`
	Category    string    `json:"category"`
	Difficulty  string    `json:"difficulty"`
	Question    string    `json:"question"`
	Options     []string  `json:"options"`
	Answer      int32     `json:"answer"`
	Explanation *string   `json:"explanation,omitempty"`
	ImageURL    *string   `json:"imageUrl,omitempty"`
	UsageCount  int32     `json:"usageCount"`
	IsActive    bool      `json:"isActive"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Mutation struct {
}

type OXQuiz struct {
	ID          string    `json:"id"`
	Category    string    `json:"category"`
	Difficulty  string    `json:"difficulty"`
	Question    string    `json:"question"`
	Answer      bool      `json:"answer"`
	Explanation *string   `json:"explanation,omitempty"`
	UsageCount  int32     `json:"usageCount"`
	IsActive    bool      `json:"isActive"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Player struct {
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
	Score       int32  `json:"score"`
	IsReady     bool   `json:"isReady"`
}

type PlayerStats struct {
	Username   string    `json:"username"`
	GameType   string    `json:"gameType"`
	TotalGames int32     `json:"totalGames"`
	TotalWins  int32     `json:"totalWins"`
	TotalScore int32     `json:"totalScore"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Query struct {
}

type UpdateUserInput struct {
	DisplayName *string `json:"displayName,omitempty"`
	Email       *string `json:"email,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
}

type User struct {
	ID          string    `json:"id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"displayName"`
	Email       *string   `json:"email,omitempty"`
	AvatarURL   *string   `json:"avatarUrl,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type GameStatus string

const (
	GameStatusWaiting  GameStatus = "WAITING"
	GameStatusPlaying  GameStatus = "PLAYING"
	GameStatusFinished GameStatus = "FINISHED"
)

var AllGameStatus = []GameStatus{
	GameStatusWaiting,
	GameStatusPlaying,
	GameStatusFinished,
}

func (e GameStatus) IsValid() bool {
	switch e {
	case GameStatusWaiting, GameStatusPlaying, GameStatusFinished:
		return true
	}
	return false
}

func (e GameStatus) String() string {
	return string(e)
}

func (e *GameStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameStatus", str)
	}
	return nil
}

func (e GameStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GameType string

const (
	GameTypeOx        GameType = "OX"
	GameTypeQa        GameType = "QA"
	GameTypeWordchain GameType = "WORDCHAIN"
)

var AllGameType = []GameType{
	GameTypeOx,
	GameTypeQa,
	GameTypeWordchain,
}

func (e GameType) IsValid() bool {
	switch e {
	case GameTypeOx, GameTypeQa, GameTypeWordchain:
		return true
	}
	return false
}

func (e GameType) String() string {
	return string(e)
}

func (e *GameType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameType", str)
	}
	return nil
}

func (e GameType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
