// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ChatMessage struct {
	ID          string    `json:"id"`
	RoomID      string    `json:"roomId"`
	Username    string    `json:"username"`
	DisplayName string    `json:"displayName"`
	Message     string    `json:"message"`
	Timestamp   time.Time `json:"timestamp"`
}

type CreateGameRoomInput struct {
	Name         string   `json:"name"`
	GameType     GameType `json:"gameType"`
	MaxPlayers   int32    `json:"maxPlayers"`
	TotalRounds  int32    `json:"totalRounds"`
	HostUsername string   `json:"hostUsername"`
	IsPrivate    *bool    `json:"isPrivate,omitempty"`
	Password     *string  `json:"password,omitempty"`
}

type CreateUserInput struct {
	Username    string  `json:"username"`
	DisplayName string  `json:"displayName"`
	Email       *string `json:"email,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
}

type ErrorEvent struct {
	Code      string    `json:"code"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
}

type GameConfig struct {
	MaxPlayers    int32 `json:"maxPlayers"`
	RoundDuration int32 `json:"roundDuration"`
	DrawingTime   int32 `json:"drawingTime"`
	GuessingTime  int32 `json:"guessingTime"`
	RoundsPerGame int32 `json:"roundsPerGame"`
}

type GameEvent struct {
	Type        GameEventType `json:"type"`
	RoomID      string        `json:"roomId"`
	Username    *string       `json:"username,omitempty"`
	DisplayName *string       `json:"displayName,omitempty"`
	Data        *string       `json:"data,omitempty"`
	Timestamp   time.Time     `json:"timestamp"`
}

// GameRoom represents a multiplayer game session.
// Supports OX quiz, QA quiz, and wordchain game modes.
type GameRoom struct {
	// Unique room identifier (UUID)
	ID string `json:"id"`
	// Room display name
	Name string `json:"name"`
	// Game mode: OX, QA, or WORDCHAIN
	GameType GameType `json:"gameType"`
	// Current game status
	Status GameStatus `json:"status"`
	// Current round number (1-based)
	CurrentRound int32 `json:"currentRound"`
	// Total rounds in this game (default: 5)
	TotalRounds int32 `json:"totalRounds"`
	// List of players in the room
	Players []*Player `json:"players"`
	// Maximum allowed players (2-10)
	MaxPlayers int32 `json:"maxPlayers"`
	// Username of the room host
	HostUsername string `json:"hostUsername"`
	// Quiz IDs already used in current game
	UsedQuizIds []string `json:"usedQuizIds"`
	// Whether room requires password
	IsPrivate bool `json:"isPrivate"`
	// Room password (only for private rooms)
	Password *string `json:"password,omitempty"`
	// Room creation timestamp
	CreatedAt time.Time `json:"createdAt"`
}

// GeneralQuiz represents a multiple-choice question (4 options).
// Used in QA game mode.
type GeneralQuiz struct {
	// Unique quiz ID (Snowflake)
	ID string `json:"id"`
	// Quiz category (e.g., Math, Geography)
	Category string `json:"category"`
	// Difficulty level: easy, medium, hard
	Difficulty string `json:"difficulty"`
	// The question text
	Question string `json:"question"`
	// Array of 4 answer options
	Options []string `json:"options"`
	// Correct answer index (0-3)
	Answer int32 `json:"answer"`
	// Optional explanation for the answer
	Explanation *string `json:"explanation,omitempty"`
	// Optional image URL for visual questions
	ImageURL *string `json:"imageUrl,omitempty"`
	// Number of times this quiz has been used
	UsageCount int32 `json:"usageCount"`
	// Whether this quiz is active
	IsActive bool `json:"isActive"`
	// Quiz creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

type Invitation struct {
	ID        string       `json:"id"`
	RoomID    string       `json:"roomId"`
	Room      *GameRoom    `json:"room"`
	InviterID string       `json:"inviterId"`
	Inviter   *User        `json:"inviter"`
	InviteeID string       `json:"inviteeId"`
	Invitee   *User        `json:"invitee"`
	Status    InviteStatus `json:"status"`
	CreatedAt time.Time    `json:"createdAt"`
	ExpiresAt time.Time    `json:"expiresAt"`
}

type Mutation struct {
}

// OXQuiz represents a True/False question.
// Used in OX game mode.
type OXQuiz struct {
	// Unique quiz ID (Snowflake)
	ID string `json:"id"`
	// Quiz category (e.g., Science, History)
	Category string `json:"category"`
	// Difficulty level: easy, medium, hard
	Difficulty string `json:"difficulty"`
	// The question text
	Question string `json:"question"`
	// Correct answer: true or false
	Answer bool `json:"answer"`
	// Optional explanation for the answer
	Explanation *string `json:"explanation,omitempty"`
	// Number of times this quiz has been used
	UsageCount int32 `json:"usageCount"`
	// Whether this quiz is active
	IsActive bool `json:"isActive"`
	// Quiz creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

type Player struct {
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
	Score       int32  `json:"score"`
	IsReady     bool   `json:"isReady"`
}

type PlayerStats struct {
	Username   string    `json:"username"`
	GameType   string    `json:"gameType"`
	TotalGames int32     `json:"totalGames"`
	TotalWins  int32     `json:"totalWins"`
	TotalScore int32     `json:"totalScore"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Query struct {
}

type Subscription struct {
}

type UpdateGameRoomInput struct {
	Name        *string `json:"name,omitempty"`
	MaxPlayers  *int32  `json:"maxPlayers,omitempty"`
	TotalRounds *int32  `json:"totalRounds,omitempty"`
	IsPrivate   *bool   `json:"isPrivate,omitempty"`
	Password    *string `json:"password,omitempty"`
}

type UpdateUserInput struct {
	DisplayName *string `json:"displayName,omitempty"`
	Email       *string `json:"email,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
}

// User represents a game player account.
// Username is unique and used as the primary identifier.
type User struct {
	// Unique identifier (Snowflake ID)
	ID string `json:"id"`
	// Unique username (3-20 characters, login ID)
	Username string `json:"username"`
	// Display name shown in game (can be duplicate)
	DisplayName string `json:"displayName"`
	// Optional email address
	Email *string `json:"email,omitempty"`
	// Optional profile image URL
	AvatarURL *string `json:"avatarUrl,omitempty"`
	// Account creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

type WordchainPrompt struct {
	Word string  `json:"word"`
	Hint *string `json:"hint,omitempty"`
}

type GameEventType string

const (
	GameEventTypePlayerJoined    GameEventType = "PLAYER_JOINED"
	GameEventTypePlayerLeft      GameEventType = "PLAYER_LEFT"
	GameEventTypePlayerReady     GameEventType = "PLAYER_READY"
	GameEventTypeHostChanged     GameEventType = "HOST_CHANGED"
	GameEventTypeRoundStarted    GameEventType = "ROUND_STARTED"
	GameEventTypeRoundEnded      GameEventType = "ROUND_ENDED"
	GameEventTypeAnswerSubmitted GameEventType = "ANSWER_SUBMITTED"
	GameEventTypeCorrectAnswer   GameEventType = "CORRECT_ANSWER"
	GameEventTypeWrongAnswer     GameEventType = "WRONG_ANSWER"
	GameEventTypeGameEnded       GameEventType = "GAME_ENDED"
)

var AllGameEventType = []GameEventType{
	GameEventTypePlayerJoined,
	GameEventTypePlayerLeft,
	GameEventTypePlayerReady,
	GameEventTypeHostChanged,
	GameEventTypeRoundStarted,
	GameEventTypeRoundEnded,
	GameEventTypeAnswerSubmitted,
	GameEventTypeCorrectAnswer,
	GameEventTypeWrongAnswer,
	GameEventTypeGameEnded,
}

func (e GameEventType) IsValid() bool {
	switch e {
	case GameEventTypePlayerJoined, GameEventTypePlayerLeft, GameEventTypePlayerReady, GameEventTypeHostChanged, GameEventTypeRoundStarted, GameEventTypeRoundEnded, GameEventTypeAnswerSubmitted, GameEventTypeCorrectAnswer, GameEventTypeWrongAnswer, GameEventTypeGameEnded:
		return true
	}
	return false
}

func (e GameEventType) String() string {
	return string(e)
}

func (e *GameEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameEventType", str)
	}
	return nil
}

func (e GameEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameEventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameEventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GameStatus string

const (
	GameStatusWaiting  GameStatus = "WAITING"
	GameStatusPlaying  GameStatus = "PLAYING"
	GameStatusFinished GameStatus = "FINISHED"
)

var AllGameStatus = []GameStatus{
	GameStatusWaiting,
	GameStatusPlaying,
	GameStatusFinished,
}

func (e GameStatus) IsValid() bool {
	switch e {
	case GameStatusWaiting, GameStatusPlaying, GameStatusFinished:
		return true
	}
	return false
}

func (e GameStatus) String() string {
	return string(e)
}

func (e *GameStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameStatus", str)
	}
	return nil
}

func (e GameStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GameType string

const (
	GameTypeOx        GameType = "OX"
	GameTypeQa        GameType = "QA"
	GameTypeWordchain GameType = "WORDCHAIN"
)

var AllGameType = []GameType{
	GameTypeOx,
	GameTypeQa,
	GameTypeWordchain,
}

func (e GameType) IsValid() bool {
	switch e {
	case GameTypeOx, GameTypeQa, GameTypeWordchain:
		return true
	}
	return false
}

func (e GameType) String() string {
	return string(e)
}

func (e *GameType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameType", str)
	}
	return nil
}

func (e GameType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InviteStatus string

const (
	InviteStatusPending  InviteStatus = "PENDING"
	InviteStatusAccepted InviteStatus = "ACCEPTED"
	InviteStatusRejected InviteStatus = "REJECTED"
	InviteStatusExpired  InviteStatus = "EXPIRED"
)

var AllInviteStatus = []InviteStatus{
	InviteStatusPending,
	InviteStatusAccepted,
	InviteStatusRejected,
	InviteStatusExpired,
}

func (e InviteStatus) IsValid() bool {
	switch e {
	case InviteStatusPending, InviteStatusAccepted, InviteStatusRejected, InviteStatusExpired:
		return true
	}
	return false
}

func (e InviteStatus) String() string {
	return string(e)
}

func (e *InviteStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InviteStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InviteStatus", str)
	}
	return nil
}

func (e InviteStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InviteStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InviteStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OXChoice string

const (
	OXChoiceO OXChoice = "O"
	OXChoiceX OXChoice = "X"
)

var AllOXChoice = []OXChoice{
	OXChoiceO,
	OXChoiceX,
}

func (e OXChoice) IsValid() bool {
	switch e {
	case OXChoiceO, OXChoiceX:
		return true
	}
	return false
}

func (e OXChoice) String() string {
	return string(e)
}

func (e *OXChoice) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OXChoice(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OXChoice", str)
	}
	return nil
}

func (e OXChoice) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OXChoice) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OXChoice) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
