// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ChatMessage struct {
	ID          string    `json:"id"`
	RoomID      string    `json:"roomId"`
	Username    string    `json:"username"`
	DisplayName string    `json:"displayName"`
	Message     string    `json:"message"`
	Timestamp   time.Time `json:"timestamp"`
}

type CreateGameRoomInput struct {
	Name         string   `json:"name"`
	GameType     GameType `json:"gameType"`
	MaxPlayers   int32    `json:"maxPlayers"`
	TotalRounds  int32    `json:"totalRounds"`
	HostUsername string   `json:"hostUsername"`
	IsPrivate    *bool    `json:"isPrivate,omitempty"`
	Password     *string  `json:"password,omitempty"`
}

type CreateUserInput struct {
	Username    string  `json:"username"`
	DisplayName string  `json:"displayName"`
	Email       *string `json:"email,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
}

type ErrorEvent struct {
	Code      string    `json:"code"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
}

type GameConfig struct {
	MaxPlayers    int32 `json:"maxPlayers"`
	RoundDuration int32 `json:"roundDuration"`
	DrawingTime   int32 `json:"drawingTime"`
	GuessingTime  int32 `json:"guessingTime"`
	RoundsPerGame int32 `json:"roundsPerGame"`
}

type GameEvent struct {
	Type        GameEventType `json:"type"`
	RoomID      string        `json:"roomId"`
	Username    *string       `json:"username,omitempty"`
	DisplayName *string       `json:"displayName,omitempty"`
	Data        *string       `json:"data,omitempty"`
	Timestamp   time.Time     `json:"timestamp"`
}

// 멀티플레이어 게임 세션을 나타냅니다.
// OX 퀴즈, QA 퀴즈, 끝말잇기 게임 모드를 지원합니다.
type GameRoom struct {
	// 고유 게임방 식별자 (UUID)
	ID string `json:"id"`
	// 게임방 표시 이름
	Name string `json:"name"`
	// 게임 모드: OX, QA, 또는 WORDCHAIN
	GameType GameType `json:"gameType"`
	// 현재 게임 상태
	Status GameStatus `json:"status"`
	// 현재 라운드 번호 (1부터 시작)
	CurrentRound int32 `json:"currentRound"`
	// 총 라운드 수 (기본값: 5)
	TotalRounds int32 `json:"totalRounds"`
	// 게임방 내 플레이어 목록
	Players []*Player `json:"players"`
	// 최대 플레이어 수 (2-10명)
	MaxPlayers int32 `json:"maxPlayers"`
	// 방장 사용자명
	HostUsername string `json:"hostUsername"`
	// 현재 게임에서 사용된 퀴즈 ID 목록
	UsedQuizIds []string `json:"usedQuizIds"`
	// 비공개방 여부
	IsPrivate bool `json:"isPrivate"`
	// 게임방 비밀번호 (비공개방만)
	Password *string `json:"password,omitempty"`
	// 게임방 생성 시각
	CreatedAt time.Time `json:"createdAt"`
}

// 4지선다 퀴즈를 나타냅니다.
// QA 게임 모드에서 사용됩니다.
type GeneralQuiz struct {
	// 고유 퀴즈 ID (Snowflake)
	ID string `json:"id"`
	// 퀴즈 카테고리 (예: 수학, 지리)
	Category string `json:"category"`
	// 난이도: easy, medium, hard
	Difficulty string `json:"difficulty"`
	// 문제 텍스트
	Question string `json:"question"`
	// 4개의 선택지 배열
	Options []string `json:"options"`
	// 정답 인덱스 (0-3)
	Answer int32 `json:"answer"`
	// 정답 설명 (선택사항)
	Explanation *string `json:"explanation,omitempty"`
	// 시각적 문제를 위한 이미지 URL (선택사항)
	ImageURL *string `json:"imageUrl,omitempty"`
	// 이 퀴즈가 사용된 횟수
	UsageCount int32 `json:"usageCount"`
	// 퀴즈 활성화 여부
	IsActive bool `json:"isActive"`
	// 퀴즈 생성 시각
	CreatedAt time.Time `json:"createdAt"`
	// 마지막 업데이트 시각
	UpdatedAt time.Time `json:"updatedAt"`
}

type Invitation struct {
	ID        string       `json:"id"`
	RoomID    string       `json:"roomId"`
	Room      *GameRoom    `json:"room"`
	InviterID string       `json:"inviterId"`
	Inviter   *User        `json:"inviter"`
	InviteeID string       `json:"inviteeId"`
	Invitee   *User        `json:"invitee"`
	Status    InviteStatus `json:"status"`
	CreatedAt time.Time    `json:"createdAt"`
	ExpiresAt time.Time    `json:"expiresAt"`
}

type Mutation struct {
}

// OX 퀴즈 (참/거짓 문제)를 나타냅니다.
// OX 게임 모드에서 사용됩니다.
type OXQuiz struct {
	// 고유 퀴즈 ID (Snowflake)
	ID string `json:"id"`
	// 퀴즈 카테고리 (예: 과학, 역사)
	Category string `json:"category"`
	// 난이도: easy, medium, hard
	Difficulty string `json:"difficulty"`
	// 문제 텍스트
	Question string `json:"question"`
	// 정답: true 또는 false
	Answer bool `json:"answer"`
	// 정답 설명 (선택사항)
	Explanation *string `json:"explanation,omitempty"`
	// 이 퀴즈가 사용된 횟수
	UsageCount int32 `json:"usageCount"`
	// 퀴즈 활성화 여부
	IsActive bool `json:"isActive"`
	// 퀴즈 생성 시각
	CreatedAt time.Time `json:"createdAt"`
	// 마지막 업데이트 시각
	UpdatedAt time.Time `json:"updatedAt"`
}

type Player struct {
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
	Score       int32  `json:"score"`
	IsReady     bool   `json:"isReady"`
}

type PlayerStats struct {
	Username   string    `json:"username"`
	GameType   string    `json:"gameType"`
	TotalGames int32     `json:"totalGames"`
	TotalWins  int32     `json:"totalWins"`
	TotalScore int32     `json:"totalScore"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Query struct {
}

type Subscription struct {
}

type UpdateGameRoomInput struct {
	Name        *string `json:"name,omitempty"`
	MaxPlayers  *int32  `json:"maxPlayers,omitempty"`
	TotalRounds *int32  `json:"totalRounds,omitempty"`
	IsPrivate   *bool   `json:"isPrivate,omitempty"`
	Password    *string `json:"password,omitempty"`
}

type UpdateUserInput struct {
	DisplayName *string `json:"displayName,omitempty"`
	Email       *string `json:"email,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
}

// 게임 플레이어 계정을 나타냅니다.
// Username은 고유하며 주요 식별자로 사용됩니다.
type User struct {
	// 고유 식별자 (Snowflake ID)
	ID string `json:"id"`
	// 고유 사용자명 (3-20자, 로그인 ID)
	Username string `json:"username"`
	// 게임 내 표시 이름 (중복 가능)
	DisplayName string `json:"displayName"`
	// 선택적 이메일 주소
	Email *string `json:"email,omitempty"`
	// 선택적 프로필 이미지 URL
	AvatarURL *string `json:"avatarUrl,omitempty"`
	// 계정 생성 시각
	CreatedAt time.Time `json:"createdAt"`
	// 마지막 업데이트 시각
	UpdatedAt time.Time `json:"updatedAt"`
}

type WordchainPrompt struct {
	Word string  `json:"word"`
	Hint *string `json:"hint,omitempty"`
}

type GameEventType string

const (
	GameEventTypePlayerJoined    GameEventType = "PLAYER_JOINED"
	GameEventTypePlayerLeft      GameEventType = "PLAYER_LEFT"
	GameEventTypePlayerReady     GameEventType = "PLAYER_READY"
	GameEventTypeHostChanged     GameEventType = "HOST_CHANGED"
	GameEventTypeRoundStarted    GameEventType = "ROUND_STARTED"
	GameEventTypeRoundEnded      GameEventType = "ROUND_ENDED"
	GameEventTypeAnswerSubmitted GameEventType = "ANSWER_SUBMITTED"
	GameEventTypeCorrectAnswer   GameEventType = "CORRECT_ANSWER"
	GameEventTypeWrongAnswer     GameEventType = "WRONG_ANSWER"
	GameEventTypeGameEnded       GameEventType = "GAME_ENDED"
)

var AllGameEventType = []GameEventType{
	GameEventTypePlayerJoined,
	GameEventTypePlayerLeft,
	GameEventTypePlayerReady,
	GameEventTypeHostChanged,
	GameEventTypeRoundStarted,
	GameEventTypeRoundEnded,
	GameEventTypeAnswerSubmitted,
	GameEventTypeCorrectAnswer,
	GameEventTypeWrongAnswer,
	GameEventTypeGameEnded,
}

func (e GameEventType) IsValid() bool {
	switch e {
	case GameEventTypePlayerJoined, GameEventTypePlayerLeft, GameEventTypePlayerReady, GameEventTypeHostChanged, GameEventTypeRoundStarted, GameEventTypeRoundEnded, GameEventTypeAnswerSubmitted, GameEventTypeCorrectAnswer, GameEventTypeWrongAnswer, GameEventTypeGameEnded:
		return true
	}
	return false
}

func (e GameEventType) String() string {
	return string(e)
}

func (e *GameEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameEventType", str)
	}
	return nil
}

func (e GameEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameEventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameEventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GameStatus string

const (
	GameStatusWaiting  GameStatus = "WAITING"
	GameStatusPlaying  GameStatus = "PLAYING"
	GameStatusFinished GameStatus = "FINISHED"
)

var AllGameStatus = []GameStatus{
	GameStatusWaiting,
	GameStatusPlaying,
	GameStatusFinished,
}

func (e GameStatus) IsValid() bool {
	switch e {
	case GameStatusWaiting, GameStatusPlaying, GameStatusFinished:
		return true
	}
	return false
}

func (e GameStatus) String() string {
	return string(e)
}

func (e *GameStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameStatus", str)
	}
	return nil
}

func (e GameStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GameType string

const (
	GameTypeOx        GameType = "OX"
	GameTypeQa        GameType = "QA"
	GameTypeWordchain GameType = "WORDCHAIN"
)

var AllGameType = []GameType{
	GameTypeOx,
	GameTypeQa,
	GameTypeWordchain,
}

func (e GameType) IsValid() bool {
	switch e {
	case GameTypeOx, GameTypeQa, GameTypeWordchain:
		return true
	}
	return false
}

func (e GameType) String() string {
	return string(e)
}

func (e *GameType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameType", str)
	}
	return nil
}

func (e GameType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InviteStatus string

const (
	InviteStatusPending  InviteStatus = "PENDING"
	InviteStatusAccepted InviteStatus = "ACCEPTED"
	InviteStatusRejected InviteStatus = "REJECTED"
	InviteStatusExpired  InviteStatus = "EXPIRED"
)

var AllInviteStatus = []InviteStatus{
	InviteStatusPending,
	InviteStatusAccepted,
	InviteStatusRejected,
	InviteStatusExpired,
}

func (e InviteStatus) IsValid() bool {
	switch e {
	case InviteStatusPending, InviteStatusAccepted, InviteStatusRejected, InviteStatusExpired:
		return true
	}
	return false
}

func (e InviteStatus) String() string {
	return string(e)
}

func (e *InviteStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InviteStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InviteStatus", str)
	}
	return nil
}

func (e InviteStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InviteStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InviteStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OXChoice string

const (
	OXChoiceO OXChoice = "O"
	OXChoiceX OXChoice = "X"
)

var AllOXChoice = []OXChoice{
	OXChoiceO,
	OXChoiceX,
}

func (e OXChoice) IsValid() bool {
	switch e {
	case OXChoiceO, OXChoiceX:
		return true
	}
	return false
}

func (e OXChoice) String() string {
	return string(e)
}

func (e *OXChoice) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OXChoice(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OXChoice", str)
	}
	return nil
}

func (e OXChoice) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OXChoice) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OXChoice) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
